feat: template
lenra-io/template-php pull request #21
Opened 2022-11-28 13:42 UTC by pichoemr

#__ 

## Checklist
- [ ] I didn't over-scope my PR
- [ ] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I did not include breaking changes
- [ ] I included unit tests that cover my changes
- [ ] I added/updated the documentation about my changes
- [ ] I made my own code-review before requesting one

## Description of the changes

## Technical highlight/advice

2022-11-29 11:57 UTC, taorepoara requested changes

2022-11-29 11:57 UTC, taorepoara commented on manifest.php
> +  "widgets" => array(
Widgets and listeners are deprecated from the manifest

2022-11-29 11:57 UTC, taorepoara commented on .lenra/Dockerfile
> +# syntax=docker/dockerfile:1.4
The `.lenra` directory should be ignored

2022-11-30 13:18 UTC, taorepoara requested changes

2022-11-30 13:18 UTC, taorepoara commented on index.php
> +$app->post('/function/{appUuid}', function (Request $request, Response $response, array $args) {
What does the `function/{appUuid}` is made for ?

2022-11-30 13:18 UTC, taorepoara commented on index.php
> +        return $response->withHeader('Content-Type', 'img/png');
Is the content type needed ? If yes, you should determine it from the file extension, if not remove it

2022-11-30 13:18 UTC, taorepoara commented on listeners/increment.php
> +    $counter = json_decode(getDoc($api, "counter", $props["id"])->getBody(), true);
You should decode the JSON in the `getDoc` method:

```suggestion
    $counter = getDoc($api, "counter", $props["id"]);
```

2022-11-30 13:18 UTC, taorepoara commented on listeners/onEnvStart.php
> +    $counters = json_decode($res->getBody());
You should decode the JSON in the `executeQuery` method:

```suggestion
    $counters = executeQuery($api, "counter", array(
        "user" => "global"
    ));
```

2022-11-30 13:18 UTC, taorepoara commented on listeners/onUserFirstJoin.php
> +    $counters = json_decode($res->getBody());
Same as erlier:
```suggestion
    $counters = executeQuery($api, "counter", array(
        "user" => "@me"
    ));
```

2022-12-01 08:37 UTC, pichoemr commented on index.php
> +$app->post('/function/{appUuid}', function (Request $request, Response $response, array $args) {
To accept post requests on /function/{appUuid}, {appUuid} is a parameter of the url so we accept requests for any appUuid passed, we also accept /fucntion/test for dev-tool requests.

2022-12-07 12:44 UTC, taorepoara commented on index.php
> +$app->post('/function/{appUuid}', function (Request $request, Response $response, array $args) {
Why does the dev-tool call the app with this path ? Can you look into the dev-tool please ?

2022-12-07 12:46 UTC, taorepoara commented
You should add informations to the `README.md` just like in the Rust template.

2022-12-07 12:53 UTC, taorepoara commented
I have this error when I try to use the template: `[200]: POST /function/test - Uncaught Error: Failed opening required 'vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /app/index.php:7`

2022-12-07 16:09 UTC, taorepoara requested changes

2022-12-07 16:09 UTC, taorepoara commented on index.php
> +$app->post('/function/{appUuid}', function (Request $request, Response $response, array $args) {
Should be replaced with a wildcard:

```suggestion
$app->post('/{path:.*}', function (Request $request, Response $response, array $args) {
```

2022-12-07 16:09 UTC, taorepoara commented on lenra.yml
> +          - composer
```suggestion
          - composer i
```

2022-12-13 09:51 UTC, pichoemr commented
@taorepoara  I test `lenra check template` on the template, i got an error:
```
manifest            : Error
    manifest:unexpectedError
        Error loading manifest checker data: Request(Transport(Transport { kind: ConnectionFailed, message: Some("Connect error"), url: Some(Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(8080), path: "/", query: None, fragment: None }), source: Some(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }) }))
widget:main         : Error
    widget:main:unexpectedError
        Error loading widget:main checker data: Request(Transport(Transport { kind: ConnectionFailed, message: Some("Connect error"), url: Some(Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(8080), path: "/", query: None, fragment: None }), source: Some(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }) }))
widget:menu         : Error
    widget:menu:unexpectedError
        Error loading widget:menu checker data: Request(Transport(Transport { kind: ConnectionFailed, message: Some("Connect error"), url: Some(Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(8080), path: "/", query: None, fragment: None }), source: Some(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }) }))
widget:home         : Error
    widget:home:unexpectedError
        Error loading widget:home checker data: Request(Transport(Transport { kind: ConnectionFailed, message: Some("Connect error"), url: Some(Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(8080), path: "/", query: None, fragment: None }), source: Some(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }) }))
widget:counter      : Error
    widget:counter:unexpectedError
        Error loading widget:counter checker data: Request(Transport(Transport { kind: ConnectionFailed, message: Some("Connect error"), url: Some(Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(8080), path: "/", query: None, fragment: None }), source: Some(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }) }))
```

2023-01-03 08:21 UTC, taorepoara submitted a review, later dismissed

2023-01-04 08:14 UTC, taorepoara requested changes

2023-01-04 08:14 UTC, taorepoara commented on README.md
> +```
Maybe replace the `build` and `start` by the `dev` command ?

```suggestion
To run the PHP template you can use the `dev` command that will build and start your app and enter in a custom terminal:

```console
lenra dev
```
```

2024-02-06 13:54 UTC, taorepoara commented
Merge this and edit the README to say the project is deprecated and archived to to use the FrankenPHP template

2024-02-07 12:36 UTC, merged